# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: postalcodes
      type: github
      endpoint: science-automation
      name: science-automation/postalcodes

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# NOTE: we dont have zip files for gr
steps:
- checkout: self
- checkout: postalcodes
- script: |
    cd /home/vsts/work/1/s/postalcodes
    ls
  displayName: 'check we have postalcodes'
- template: artifact.yaml
  parameters:
    param: ["ua", "fr", "es", "se", "de", "fi", "no", "pl", "it", "gb", "ro", "by", "bg", "is", "pt", "cz", "dk", "hu", "rs", "at", "ie", "lt", "lv", "hr", "ba", "sk", "ee", "nl", "ch", "md", "be", "al", "mk", "si", "me", "cy", "lu", "fo", "ad", "mt", "li", "gg", "sm", "gi", "mc", "va"]
